config/routes.rb
Rails.application.routes.draw do
  resources :controllers
  resources :shops
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'welcome/about', to: 'welcome#about'
  get 'receipts', to: 'receipts#index'
  resources :receipts
  resources :articles


end

app/models/receipt.rb
class Receipt < ApplicationRecord
  has_many :articles, dependent: :destroy
  belongs_to :shop
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :set_receipt, only: [:show, :edit, :update, :destroy]

  # GET /receipts
  # GET /receipts.json
  def index
    @receipts = Receipt.all
    @articles = Article.all
    @shop = Shop.all
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show
  end

  # GET /receipts/new
  def new
    @receipt = Receipt.new
    @receipt.shop_id = params{:id}
  end

  # GET /receipts/1/edit
  def edit
  end

  # POST /receipts
  # POST /receipts.json
  def create
    @receipt = Receipt.new(receipt_params)
    @receipt.shop_id = params{:id}
    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: 'Receipt was successfully created.' }
        format.json { render :show, status: :created, location: @receipt }
      else
        format.html { render :new }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receipts/1
  # PATCH/PUT /receipts/1.json
  def update
    respond_to do |format|
      if @receipt.update(receipt_params)
        format.html { redirect_to @receipt, notice: 'Receipt was successfully updated.' }
        format.json { render :show, status: :ok, location: @receipt }
      else
        format.html { render :edit }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1
  # DELETE /receipts/1.json
  def destroy
    @receipt.destroy
    respond_to do |format|
      format.html { redirect_to receipts_url, notice: 'Receipt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipt
      @receipt = Receipt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receipt_params
      params.require(:receipt).permit(:purchasedate, :paymentmethode, :shop_id)
    end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/receipts/_form.html.erb
<%= form_for(receipt) do |f| %>
  <% if receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
      <% receipt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :purchasedate %>
    <%= f.date_select :purchasedate %>
  </div>

  <div class="field">
    <%= f.label :paymentmethode %>
    <%= f.text_field :paymentmethode %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/receipts/edit.html.erb
<h1>Editing Receipt</h1>

<%= render 'form', receipt: @receipt %>

<%= link_to 'Show', @receipt %> |
<%= link_to 'Back', receipts_path %>

app/views/receipts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Receipts</h1>

<table>
  <thead>
    <tr>
      <th>Purchasedate</th>
      <th>Paymentmethode</th>
      <th>Shop</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @receipts.each do |receipt| %>
      <tr>
        <td><%= receipt.purchasedate %></td>
        <td><%= receipt.paymentmethode %></td>
        <% sjop = shop.select{|i| i = receipt.shop_id} %>
        <td><%= sjop %></td>
        <td><%= link_to 'Show', receipt %></td>
        <td><%= link_to 'Edit', edit_receipt_path(receipt) %></td>
        <td><%= link_to 'Destroy', receipt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receipt', new_receipt_path %>

app/views/receipts/new.html.erb
<h1>New Receipt</h1>
<%= params[:id] %>
<%= render 'form', receipt: @receipt %>
<%= link_to 'Back', receipts_path %>

app/views/receipts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Purchasedate:</strong>
  <%= @receipt.purchasedate %>
</p>

<p>
  <strong>Paymentmethode:</strong>
  <%= @receipt.paymentmethode %>
</p>

<%= link_to 'Edit', edit_receipt_path(@receipt) %> |
<%= link_to 'Back', receipts_path %>